export const DELTA_X = '--delta-x';
export const DELTA_Y = '--delta-y';
export const INTERSECTION_RATIO = 1 / 2;
export const DRAGGED_TRANSLATE = 'translate(var(--delta-x), var(--delta-y))';
export const COMMON_TRANSITION = 'transform 0.3s';
export const COMMON_TRANSLATE = 'translateY(var(--delta-y))';
export const TASK_MINI_HEIGHT = 150;
export const GAP = 16;
export const SINGLE_VERTICAL_MOVE = TASK_MINI_HEIGHT + GAP;
